// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type CheckRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{1}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type CheckResponse struct {
	Exists               bool     `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{2}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "service.AddRequest")
	proto.RegisterType((*CheckRequest)(nil), "service.CheckRequest")
	proto.RegisterType((*CheckResponse)(nil), "service.CheckResponse")
}

func init() { proto.RegisterFile("filter.proto", fileDescriptor_1f5303cab7a20d6f) }

var fileDescriptor_1f5303cab7a20d6f = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0xd0, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0x06, 0xf0, 0x2e, 0xc5, 0xaa, 0x43, 0x05, 0x19, 0x71, 0x91, 0x15, 0xa4, 0xec, 0x45, 0x2f,
	0x26, 0xa0, 0x1e, 0xbc, 0xb6, 0xa2, 0x0f, 0xb0, 0xde, 0xbc, 0xb5, 0xbb, 0xd3, 0xb8, 0x34, 0xdb,
	0x89, 0x49, 0x2a, 0xed, 0xdd, 0x07, 0x97, 0x4d, 0xe2, 0x1f, 0x04, 0x4f, 0x49, 0x86, 0x2f, 0xf9,
	0x7e, 0x04, 0xc6, 0xcb, 0x56, 0x7b, 0xb2, 0xc2, 0x58, 0xf6, 0x8c, 0xfb, 0x8e, 0xec, 0x7b, 0x5b,
	0x53, 0x71, 0xae, 0x98, 0x95, 0x26, 0x19, 0xc6, 0x8b, 0xcd, 0x52, 0x52, 0x67, 0xfc, 0x2e, 0xa6,
	0xca, 0x0b, 0x80, 0x69, 0xd3, 0x54, 0xf4, 0xb6, 0x21, 0xe7, 0xf1, 0x18, 0x86, 0x2b, 0xda, 0x9d,
	0x65, 0x93, 0xec, 0xea, 0xb0, 0xea, 0xb7, 0xe5, 0x04, 0xc6, 0x0f, 0xaf, 0x54, 0xaf, 0xfe, 0x4f,
	0x5c, 0xc2, 0x51, 0x4a, 0x38, 0xc3, 0x6b, 0x47, 0x98, 0xc3, 0x88, 0xb6, 0xad, 0xf3, 0x2e, 0xa4,
	0x0e, 0xaa, 0x74, 0xba, 0xf9, 0xc8, 0x00, 0x67, 0x9a, 0xb9, 0x7b, 0x0a, 0xcc, 0xe7, 0xc8, 0xc3,
	0x3b, 0x18, 0x4e, 0x9b, 0x06, 0x4f, 0x44, 0xf2, 0x8a, 0x1f, 0x4f, 0x91, 0x8b, 0x68, 0x17, 0x5f,
	0x76, 0xf1, 0xd8, 0xdb, 0xcb, 0x01, 0xde, 0xc3, 0x5e, 0x68, 0xc5, 0xd3, 0xef, 0x7b, 0xbf, 0x9d,
	0x45, 0xfe, 0x77, 0x1c, 0x71, 0xe5, 0x60, 0x26, 0x5f, 0xae, 0xd3, 0xa3, 0x8a, 0xf5, 0x7c, 0xad,
	0x04, 0x5b, 0x25, 0x95, 0x35, 0xb5, 0xa4, 0xed, 0xbc, 0x33, 0x9a, 0x9c, 0x8c, 0xff, 0x98, 0x96,
	0xc5, 0x28, 0x94, 0xdf, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x35, 0x3e, 0x7c, 0xfd, 0x5f, 0x01,
	0x00, 0x00,
}
